-- 코드를 입력하세요
SELECT TITLE, A.BOARD_ID, REPLY_ID, WRITER_ID, CONTENTS, DATE_FORMAT(CREATED_DATE,"%Y-%m-%d") AS CREATED_DATE
FROM USED_GOODS_REPLY A
LEFT JOIN (
    SELECT TITLE, BOARD_ID
    FROM USED_GOODS_BOARD
    WHERE DATE_FORMAT(CREATED_DATE,'%Y-%m') = '2022-10'
) B
ON A.BOARD_ID = B.BOARD_ID
WHERE TITLE IS NOT NULL
ORDER BY CREATED_DATE, TITLE