-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK A, AUTHOR B
WHERE CATEGORY = '경제'
    AND A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY PUBLISHED_DATE