-- 코드를 입력하세요
SELECT *
FROM (
    SELECT CAR_ID, A.CAR_TYPE, FLOOR(30*DAILY_FEE*(100-DISCOUNT_RATE) / 100) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    LEFT JOIN (
        SELECT CAR_TYPE, DISCOUNT_RATE
        FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
        WHERE DURATION_TYPE = '30일 이상'
    ) B
    ON A.CAR_TYPE = B.CAR_TYPE
    WHERE A.CAR_TYPE IN ('SUV', '세단')
) X
WHERE FEE >= 500000
    AND FEE < 2000000
    AND CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE_FORMAT(END_DATE,'%Y-%m') >= '2022-11'
        AND DATE_FORMAT(START_DATE,'%Y-%m') <= '2022-11'
)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC