-- 코드를 입력하세요
SELECT A.PRODUCT_ID, A.PRODUCT_NAME, PRICE*AMOUNT AS TOTAL_SALES
FROM FOOD_PRODUCT A
INNER JOIN
(
SELECT PRODUCT_ID, SUM(AMOUNT) AS AMOUNT
FROM FOOD_ORDER
WHERE MONTH(PRODUCE_DATE) = 5 AND YEAR(PRODUCE_DATE) = 2022
GROUP BY PRODUCT_ID
) B
ON A.PRODUCT_ID = B.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID