-- 코드를 입력하세요
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, COUNT(DISTINCT A.USER_ID) AS PUCHASED_USERS, ROUND(COUNT(DISTINCT A.USER_ID) / COUNT, 1) AS PUCHASED_RATIO
FROM ONLINE_SALE A
JOIN
(
    SELECT *
    FROM
    (
        SELECT USER_ID
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    ) A
    CROSS JOIN
    (
        SELECT COUNT(DISTINCT USER_ID) AS COUNT
        FROM USER_INFO
        WHERE YEAR(JOINED) = 2021
    ) B 
) B
ON A.USER_ID = B.USER_ID
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH