-- 코드를 입력하세요
SELECT APNT_NO, PT_NAME, PT_NO, X.MCDP_CD, DR_NAME, APNT_YMD
FROM (
    SELECT APNT_NO, PT_NAME, A.PT_NO, MCDP_CD, APNT_YMD, MDDR_ID
    FROM APPOINTMENT A
    JOIN PATIENT B
    ON A.PT_NO = B.PT_NO
    WHERE A.MCDP_CD = 'CS'
      AND A.APNT_CNCL_YN = 'N'
      AND DATE(A.APNT_YMD) = '2022-04-13'
) X
LEFT JOIN DOCTOR Y
ON X.MDDR_ID = Y.DR_ID
ORDER BY APNT_YMD