-- 코드를 입력하세요
# SELECT HISTORY_ID, DAILY_FEE * DAYS
SELECT HISTORY_ID, FLOOR(DAYS * DAILY_FEE * (100 - IFNULL(DISCOUNT_RATE,0)) / 100) AS FEE
FROM (
    SELECT HISTORY_ID,DATEDIFF(END_DATE, START_DATE) + 1 AS DAYS, DAILY_FEE,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE NULL
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
    LEFT JOIN CAR_RENTAL_COMPANY_CAR B
    ON A.CAR_ID = B.CAR_ID
    WHERE CAR_TYPE = '트럭'
) X
LEFT JOIN (
    SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) Y
ON X.DURATION_TYPE = Y.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC