-- 코드를 입력하세요
SELECT USER_ID, NICKNAME,
       CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS '전체주소',
       CONCAT(
       LEFT(TLNO,LENGTH(TLNO)-8),'-',
       LEFT(RIGHT(TLNO,8),4),'-',
       RIGHT(RIGHT(TLNO,8),4)
       ) AS '전화번호'
FROM USED_GOODS_USER
WHERE USER_ID
IN (
    SELECT WRITER_ID AS USER_ID
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING COUNT(WRITER_ID) > 2
)
ORDER BY USER_ID DESC